#spring:
#  application:
#    name: ssl-demo-app
#
#server:
#  port: 8443
#  ssl:
#    enabled: true
#    key-store: classpath:ssl-demo-app.p12
#    key-store-password: password
#    key-store-type: PKCS12
#    key-alias: ssl-demo-app
#    trust-store: classpath:ssl-demo-app-truststore.p12
#    trust-store-password: password
#    trust-store-type: PKCS12

spring:
  application:
    name: ssl-demo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

server:
  port: ${SERVER_PORT:8443}
  ssl:
    enabled: true
    key-store: classpath:${SSL_KEYSTORE_NAME:ssl-demo-app.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:changeit}
    key-store-type: ${SSL_KEYSTORE_TYPE:PKCS12}
    key-alias: ${SSL_KEY_ALIAS:ssl-demo-app}
    trust-store: classpath:${SSL_TRUSTSTORE_NAME:ssl-demo-app-truststore.p12}
    trust-store-password: ${SSL_TRUSTSTORE_PASSWORD:changeit}
    trust-store-type: ${SSL_TRUSTSTORE_TYPE:PKCS12}

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.example.ssldemo: DEBUG